config/routes.rb
Rails.application.routes.draw do
  resources :listings

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :address, :goal, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "FUNdWorks" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>    
      </div>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-8 columns large-offset-2">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns large-offset-2">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns large-offset-2">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns large-offset-2">
      <div class="row">
        <div class="large-6 columns">
          <%= f.label :goal %>
          <%= f.text_field :goal, placeholder: "USD" %>
        </div>
        <div class="large-6 columns">
          <%= f.label :end_date %>
          <div class="end_date">
            <%= f.date_select :end_date %>
          </div>
        </div>
      </div>
      
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns large-offset-2">
      <%= f.submit class: "button right" %>  
    </div>
  </div>
  <!-- <div class="actions">
    
  </div> -->
<% end %>

app/views/listings/edit.html.erb
<div class="row">
  <div class="large-8 columns large-offset-2">
    <h1>Edit Campaign</h1>    
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Goal</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.description %></td>
        <td><%= listing.address %></td>
        <td><%= listing.goal %></td>
        <td><%= listing.end_date %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<div class="row">
  <div class="large-8 columns large-offset-2">
    <h1>New Campaign</h1>    
  </div>
</div>


<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="row">
  <div class="large-12 colums">
    <p id="notice"><%= notice %></p>

    <h1>
      <%= @listing.name %>
    </h1>
    
  </div>
</div>


<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @listing.goal %>
</p>

<p>
  <strong>End date:</strong>
  <%= @listing.end_date %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>